_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1

min_epochs: 30
max_epochs: 500

#min_epochs: 1
#max_epochs: 1

reload_dataloaders_every_n_epochs: 1

#weights_summary: null
#progress_bar_refresh_rate: 5
#resume_from_checkpoint: null
