_target_: src.datamodules.mashup_api_matrix_datamodule.MashupApiMatrixDatamodule

data_dir: ${data_dir} # data_dir is specified in config.yaml
data_name: 'api_mashup'
batch_size: 1
num_workers: 0
pin_memory: False