_target_: src.datamodules.mtfm_datamodule.MTFMDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
data_name: 'api_mashup'
train_val_test_split: [3174, 907, 454] # 7: 2: 1
batch_size: 32
num_workers: 0
pin_memory: False
transpose: False